server.port=8080
spring.profiles.active=dev
server.error.include-message=always
spring.datasource.url=jdbc:postgresql://localhost:5432/social_media_db
spring.datasource.username=postgres
spring.datasource.password=your_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.printer.enabled=true
cloudinary.cloud_name=your_cloud_name
cloudinary.api_key=your_api_key
cloudinary.api_secret=your_api_secret
app.jwt.secret=9a4f2c3d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
# Th?i gian h?t h?n (v� d?: 86400000 ms = 1 ng�y)
app.jwt.expiration-ms=86400000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.graphql=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE