server.port=8080
server.error.include-message=always
spring.datasource.url=jdbc:postgresql://localhost:5432/social_media_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.printer.enabled=true
cloudinary.cloud_name=dtnonjckn
cloudinary.api_key=246589516945792
cloudinary.api_secret=ScnS6i3JS0vcyOTXmcacnOIjKK4
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
app.jwt.secret=9a4f2c3d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z
app.jwt.expiration-ms=86400000
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.graphql=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE